### PR TITLE
Added: Swift PM Package.swift

### PR DESCRIPTION
**Pull request by pitiphong-p**

### CODE REVIEW

**Review by igroomgrim — APPROVED** [review]
🎸

**Review by nuxzero — APPROVED** [review]

**Comment by nuxzero** [comment]
No support Carthage/CocoaPods?

**Comment by pitiphong-p** [comment]
@nuxzero We would not support CocoaPods and we will get Carthage support for free with the current setup after we tag a version

**Comment by nuxzero** [comment]
👍

**Review by Namiii — APPROVED** [review]

**Pull request merged**
